### ISSUE TITLE
Can both esp devices connect to wifi and use espnow?

### ISSUE THREAD

**Issue by clinta** [tomrusteze/esphome-esp-now#2] opened 2023-01-18 22:10 UTC
Your example has only the hub connected to wifi and homeassistant. But can both devices connect to wifi and homeassistant and still use espnow?

My use case is I'd like to have a switch and a light, both connected directly to homeassistant. But I'd like the control to happen over espnow so that control of the lights still works even if the wifi network is down.

**Comment by tomrusteze** [comment] 2023-01-19 14:10
Yes, this is definitely possible. I will soon add some extra examples that fit this use case. For now, this issues seems like a duplicate of #1

**Closed as completed by tomrusteze** 2023-01-19 14:10 UTC
